name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: sunghwanlee/swpp202101-ci

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
    - name: configure
      run: ./configure.sh /llvmscript/llvm-12.0-releaseassert/bin
    - name: make
      run: make
    - name: make test
      run: make test
